#!/usr/bin/env python3
"""Fail CI when critical files fall below stricter coverage thresholds."""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

CRITICAL_THRESHOLDS = {
    "main.py": 80.0,
    "src/agents.py": 85.0,
    "src/utils.py": 85.0,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate coverage thresholds for critical bot pipeline modules."
    )
    parser.add_argument(
        "coverage_xml",
        nargs="?",
        default="coverage.xml",
        help="Path to cobertura XML report generated by pytest-cov (default: coverage.xml).",
    )
    return parser.parse_args()


def load_line_rates(coverage_xml: Path) -> dict[str, float]:
    tree = ET.parse(coverage_xml)
    root = tree.getroot()

    file_rates: dict[str, float] = {}
    for class_node in root.findall(".//class"):
        filename = class_node.attrib.get("filename")
        line_rate = class_node.attrib.get("line-rate")
        if not filename or line_rate is None:
            continue

        # If a file appears multiple times, keep the highest fidelity aggregate.
        file_rates[filename] = max(float(line_rate) * 100, file_rates.get(filename, 0.0))

    return file_rates


def main() -> int:
    args = parse_args()
    coverage_xml = Path(args.coverage_xml)

    if not coverage_xml.exists():
        print(f"ERROR: coverage report not found: {coverage_xml}")
        return 2

    file_rates = load_line_rates(coverage_xml)

    failures: list[str] = []
    print("Critical-path coverage checks:")
    for module_path, threshold in CRITICAL_THRESHOLDS.items():
        observed = file_rates.get(module_path)
        if observed is None:
            failures.append(
                f"- {module_path}: missing from coverage report (required >= {threshold:.1f}%)"
            )
            continue

        print(f"- {module_path}: {observed:.1f}% (required >= {threshold:.1f}%)")
        if observed + 1e-9 < threshold:
            failures.append(
                f"- {module_path}: {observed:.1f}% is below required {threshold:.1f}%"
            )

    if failures:
        print("\nCoverage policy violation(s):")
        for failure in failures:
            print(failure)
        return 1

    print("\nAll critical-path modules satisfy stricter coverage requirements.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
